### PR TITLE
Move from TSlint to ESLint

### PR DESCRIPTION
**Pull request by GuyKh**
Issue #19

### CODE REVIEW

**Comment by GuyKh** [comment]
For some reason CLA fails to sign :/

**Comment by mjpitz** [comment]
What do you mean "fails to sign"? Can you attach a screenshot?

Resolves gh-19

**Review by mjpitz — APPROVED** [review]
This all looks good to me.

**Comment by mjpitz** [comment]
Verified in cla-assistant. `GuyKh - Oct 1, 2020 7:05:00 AM`

**Comment by mjpitz** [comment]
Thanks @GuyKh for your quick PR!

**Comment by GuyKh** [comment]
@mjpitz any chance you (at Indeed) will send the sweatshirts of Hacktoberfest to Israel? :( 
Despite the common assumption, we do get some cold weather around here :D

**Comment by mjpitz** [comment]
I don't think they have any geo-restrictions in place, but you'll need to reach out to the team to confirm.

**Comment by alisonjudy** [comment]
Hi @GuyKh unfortunately we're only shipping to the US. Thank you for providing a US address to ship to. We appreciate your contributions! :)

**Pull request merged**
